<template>
  <div class="q-pa-md">
    <UserTable :columns="columns" :rows="rows" :pagination="pagination" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import UserTable from "./UserTable.vue";
const pagination = ref({
  sortBy: "desc",
  descending: false,
  page: 1,
  rowsPerPage: 15,
});
const columns = [
  {
    name: "name",
    required: true,
    label: "Name",
    align: "left",
    sortable: true,
  },
  {
    name: "email",
    align: "left",
    label: "Email",
    field: "email",
    sortable: true,
  },
  {
    name: "role",
    label: "Role",
    align: "left",
    field: "role",
    sortable: true,
  },
  {
    name: "createdAt",
    label: "Created At",
    align: "left",
    field: "createdAt",
  },
  {
    name: "updatedAt",
    label: "Updated At",
    align: "left",
    field: "updatedAt",
  },

  {
    name: "actions",
    label: "Actions",
    align: "center",
    field: "actions",
  },
  // {
  //   name: "calcium",
  //   label: "Calcium (%)",
  //   field: "calcium",
  //   sortable: true,
  //   sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  // },
  // {
  //   name: "iron",
  //   label: "Iron (%)",
  //   field: "iron",
  //   sortable: true,
  //   sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  // },
];

const rows = [
  {
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-01-02",
  },
  {
    name: "Jane Doe",
    email: "jane@example.com",
    role: "User",
    createdAt: "2022-02-01",
    updatedAt: "2022-02-02",
  },
  {
    name: "Bob Smith",
    email: "bob@example.com",
    role: "Editor",
    createdAt: "2022-03-01",
    updatedAt: "2022-03-02",
  },
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "Viewer",
    createdAt: "2022-04-01",
    updatedAt: "2022-04-02",
  },
  {
    name: "Charlie Brown",
    email: "charlie@example.com",
    role: "Admin",
    createdAt: "2022-05-01",
    updatedAt: "2022-05-02",
  },
  {
    name: "Eva Martinez",
    email: "eva@example.com",
    role: "User",
    createdAt: "2022-06-01",
    updatedAt: "2022-06-02",
  },
  {
    name: "David Wilson",
    email: "david@example.com",
    role: "Editor",
    createdAt: "2022-07-01",
    updatedAt: "2022-07-02",
  },
  {
    name: "Grace Lee",
    email: "grace@example.com",
    role: "Viewer",
    createdAt: "2022-08-01",
    updatedAt: "2022-08-02",
  },
  {
    name: "Frank Adams",
    email: "frank@example.com",
    role: "Admin",
    createdAt: "2022-09-01",
    updatedAt: "2022-09-02",
  },
  {
    name: "Sophie Turner",
    email: "sophie@example.com",
    role: "User",
    createdAt: "2022-10-01",
    updatedAt: "2022-10-02",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-01-02",
  },
  {
    name: "Jane Doe",
    email: "jane@example.com",
    role: "User",
    createdAt: "2022-02-01",
    updatedAt: "2022-02-02",
  },
  {
    name: "Bob Smith",
    email: "bob@example.com",
    role: "Editor",
    createdAt: "2022-03-01",
    updatedAt: "2022-03-02",
  },
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "Viewer",
    createdAt: "2022-04-01",
    updatedAt: "2022-04-02",
  },
  {
    name: "Charlie Brown",
    email: "charlie@example.com",
    role: "Admin",
    createdAt: "2022-05-01",
    updatedAt: "2022-05-02",
  },
  {
    name: "Eva Martinez",
    email: "eva@example.com",
    role: "User",
    createdAt: "2022-06-01",
    updatedAt: "2022-06-02",
  },
  {
    name: "David Wilson",
    email: "david@example.com",
    role: "Editor",
    createdAt: "2022-07-01",
    updatedAt: "2022-07-02",
  },
  {
    name: "Grace Lee",
    email: "grace@example.com",
    role: "Viewer",
    createdAt: "2022-08-01",
    updatedAt: "2022-08-02",
  },
  {
    name: "Frank Adams",
    email: "frank@example.com",
    role: "Admin",
    createdAt: "2022-09-01",
    updatedAt: "2022-09-02",
  },
  {
    name: "Sophie Turner",
    email: "sophie@example.com",
    role: "User",
    createdAt: "2022-10-01",
    updatedAt: "2022-10-02",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-01-02",
  },
  {
    name: "Jane Doe",
    email: "jane@example.com",
    role: "User",
    createdAt: "2022-02-01",
    updatedAt: "2022-02-02",
  },
  {
    name: "Bob Smith",
    email: "bob@example.com",
    role: "Editor",
    createdAt: "2022-03-01",
    updatedAt: "2022-03-02",
  },
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "Viewer",
    createdAt: "2022-04-01",
    updatedAt: "2022-04-02",
  },
  {
    name: "Charlie Brown",
    email: "charlie@example.com",
    role: "Admin",
    createdAt: "2022-05-01",
    updatedAt: "2022-05-02",
  },
  {
    name: "Eva Martinez",
    email: "eva@example.com",
    role: "User",
    createdAt: "2022-06-01",
    updatedAt: "2022-06-02",
  },
  {
    name: "David Wilson",
    email: "david@example.com",
    role: "Editor",
    createdAt: "2022-07-01",
    updatedAt: "2022-07-02",
  },
  {
    name: "Grace Lee",
    email: "grace@example.com",
    role: "Viewer",
    createdAt: "2022-08-01",
    updatedAt: "2022-08-02",
  },
  {
    name: "Frank Adams",
    email: "frank@example.com",
    role: "Admin",
    createdAt: "2022-09-01",
    updatedAt: "2022-09-02",
  },
  {
    name: "Sophie Turner",
    email: "sophie@example.com",
    role: "User",
    createdAt: "2022-10-01",
    updatedAt: "2022-10-02",
  },
];
</script>
