<template>
  <div class="q-pa-md">
    <SourceTable :columns="columns" :rows="rows" :pagination="pagination" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import SourceTable from "./SourceTable.vue";
const pagination = ref({
  sortBy: "desc",
  descending: false,
  page: 1,
  rowsPerPage: 15,
});
const columns = [
  {
    name: "sourceName",
    required: true,
    label: "Source Name",
    field: "sourceName",
    align: "left",
  },
  {
    name: "sourceURL",
    align: "left",
    label: "Source URL",
    field: "sourceURL",
  },

  {
    name: "country",
    label: "Country",
    align: "left",
    field: "country",
  },
  {
    name: "coverage",
    label: "Coverage",
    align: "left",
    field: "coverage",
  },
  {
    name: "type",
    label: "Type",
    align: "left",
    field: "type",
  },
  {
    name: "category",
    label: "Category",
    align: "left",
    field: "category",
  },
  {
    name: "language",
    label: "Language",
    align: "left",
    field: "language",
  },
  {
    name: "format",
    label: "Format",
    align: "left",
    field: "format",
  },
  {
    name: "comment",
    label: "Comment",
    align: "left",
    field: "comment",
  },
  {
    name: "cost",
    label: "Cost",
    align: "left",
    field: "cost",
  },
  {
    name: "keyMapping",
    label: "Key Mapping",
    align: "left",
    field: "keyMapping",
  },
  {
    name: "integrations",
    label: "Integrations",
    align: "center",
    field: "integration",
  },
  {
    name: "techComments",
    label: "Tech Comments",
    align: "left",
    field: "techComments",
  },
  {
    name: "integrationStatus",
    label: "Integration Status",
    align: "left",
    field: "integrationStatus",
  },
  {
    name: "lastUpdatedBy",
    label: "Last Updated By",
    align: "left",
    field: "lastUpdatedBy",
  },
  {
    name: "updatedAt",
    label: "Updated At",
    align: "left",
    field: "updatedAt",
  },
  {
    name: "createdAt",
    label: "Created At",
    align: "left",
    field: "createdAt",
  },

  // {
  //   name: "editSource",
  //   label: "Edit Source",
  //   align: "left",
  //   field: "editSource",
  //   sortable: true,
  // },
  // {
  //   name: "clickUpTasks",
  //   label: "Click up Tasks",
  //   align: "left",
  //   field: "clickUpTasks",
  //   sortable: true,
  // },

  {
    name: "actions",
    label: "Actions",
    align: "center",
    field: "actions",
  },
];

const rows = [
  {
    sourceName:
      "French Commercial Courts - Trade and Companies Register - Infogreffe",
    sourceURL: "https://www.sirene.fr/sirene/public/accueil",
    country: "French Polynesia",
    coverage: "Complete",
    type: "Official",
    category: "AML/P",
    language: "Afrikaans",
    format: "HTML",
    comment: "comments here",
    cost: "free",
    keyMapping: "google doc link", // text-field- url
    integrations: true, // checkbox
    techComments: "tech comments",
    integrationStatus: "Done (Live)",
    lastUpdatedBy: "John Deo",
    updatedAt: "14 Jan 2024",
    createdAt: "14 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
  {
    sourceName: "Trade and Commerce Database",
    sourceURL: "https://www.tradecommerce-db.com",
    country: "DEF Republic",
    coverage: "Complete",
    type: "Unofficial",
    category: "Trade",
    language: "Spanish",
    format: "CSV",
    comment: "Duis aute irure dolor in reprehenderit.",
    cost: "Free",
    keyMapping: "https://docs.google.com/document/d/abc",
    integrations: true,
    techComments: "Duis aute irure tech comments.",
    integrationStatus: "In Progress",
    lastUpdatedBy: "Bob Smith",
    updatedAt: "16 Jan 2024",
    createdAt: "16 Jan 2024",
  },
  {
    sourceName: "XYZ Business Registry",
    sourceURL: "https://www.xyzregistry.com",
    country: "ABC Country",
    coverage: "Partial",
    type: "Official",
    category: "Financial",
    language: "English",
    format: "PDF",
    comment: "Lorem ipsum dolor sit amet.",
    cost: "Paid",
    keyMapping: "https://docs.google.com/document/d/xyz",
    integrations: false,
    techComments: "Lorem ipsum tech comments.",
    integrationStatus: "Pending",
    lastUpdatedBy: "Jane Doe",
    updatedAt: "15 Jan 2024",
    createdAt: "15 Jan 2024",
  },
];
</script>
